# Generated by Django 4.2.6 on 2023-10-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0005_mecprofile_eleprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("detalle", models.CharField(max_length=2000)),
                ("detalle_corto", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("S", "Suspención de actividades"),
                            ("C", "Suspención de clase"),
                            ("I", "Información"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("visible", models.BooleanField()),
                ("fecha_p", models.DateTimeField(auto_now_add=True)),
                ("fecha_um", models.DateTimeField(auto_now=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
