# Generated by Django 4.2.6 on 2023-10-24 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0006_comunicado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comunicado",
            old_name="fecha_p",
            new_name="fecha_publicacion",
        ),
        migrations.RenameField(
            model_name="comunicado",
            old_name="fecha_um",
            new_name="fecha_ultima_modificacion",
        ),
        migrations.RenameField(
            model_name="comunicado",
            old_name="title",
            new_name="titulo",
        ),
    ]
