# Generated by Django 4.2.6 on 2023-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_rename_fecha_p_comunicado_fecha_publicacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="entidad",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("INF", "Informatica"),
                    ("ELE", "Electronica"),
                    ("MEC", "Mecanica"),
                ],
                default="ADMIN",
                max_length=5,
            ),
        ),
    ]
