# Generated by Django 4.2.6 on 2023-10-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='ROLE',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INF', 'Informatica'), ('ELE', 'Electrica'), ('MEC', 'Mecanica')], default='ADMIN', max_length=5),
        ),
    ]
